### ISSUE TITLE
Positive Dataset problem persists

### ISSUE THREAD

**Issue by Mert18** [MeioJane/SIXray#14]
I am having trouble opening last file (.tar.gz17) which I believe contains positive dataset. Also the given .rar download links are not working. Where can I find the positive dataset? I am using windows.

**Comment by loopback-kr** [comment]
If you are using chrome, the http download link is not allowed due to security reasons. use firefox or edge

**Comment by zain18jan2000** [comment]
Hello Mert18, did you get the solution ?

**Comment by Mert18** [comment]
unfortunately no
