### ISSUE TITLE
couldn't download the dataset

### ISSUE THREAD

**Issue by ElifErarslan1** [MeioJane/SIXray#5]
Hi, I tried to download data from link. I also sent an email to obtain temporary link but I haven't received any reply yet. How can I access the dataset ?

**Comment by MeioJane** [comment]
sorry, you can send a email to miaocaijing1@kingsoft.com I will give you the temporary link, I fail to login in the email miaocaijing16@mails.ucas.ac.cn beacause of some security reason. I am so sorry for this and I will resolve this problem as soon as possible

**Comment by MeioJane** [comment]
I login in the email miaocaijing16@mails.ucas.ac.cn successgully ,you can contact me with this email
