### ISSUE TITLE
请问Annotation.zip中的是什么标签？

### ISSUE THREAD

**Issue by ZZM11** [MeioJane/SIXray#8]
positive-Annotation是正样本，那annotation里面是什么？

**Comment by ZZM11** [comment]
另外我常在论文中看到SIXRay-OD数据集，请问这个是指什么？

**Comment by MeioJane** [comment]
positive-annotation is all test positive images annotation, annotation.zip is all positive images annotation including train and test

**Comment by MeioJane** [comment]
> positive-Annotation是正样本，那annotation里面是什么？

positive-annotation is all test positive images annotation, annotation.zip is all positive images annotation including train and test

**Comment by MeioJane** [comment]
>

**Comment by MeioJane** [comment]
> 另外我常在论文中看到SIXRay-OD数据集，请问这个是指什么？

Sorry. I do not found this word SIXRay-OD in my paper. Can you give a more detailed discription?
